Ball destroying
n2oneProgrammer/pang-game pull request #12
Opened 2022-01-17 21:44 UTC by n2oneProgrammer

2022-01-17 21:47 UTC, mwawrzen approved these changes
LGTM

2022-01-17 21:51 UTC, jaanonim requested changes
Weird import

2022-01-17 21:51 UTC, jaanonim commented on models/objects/chain_bullet.py
> +                for obj in models.game_manager.GameManager().scene.objects:
This is strange. Maybe import `GameManager` instead of whole file

2022-01-17 21:51 UTC, jaanonim commented on models/objects/chain_bullet.py
> +import models.game_manager
Comment below

2022-01-18 08:28 UTC, jaanonim approved these changes

2022-01-18 10:16 UTC, merged